language: python
    - "3.6"
    - "3.6.3"
install:
    - sudo apt install python3-pip
    - pip3 install requests
    - sudo pip3 install Flask
    - sudo pip3 install flask-cors
script:
    - cd backend
    - FLASK_APP=api.py python3 -m flask run &
    - python3 -m unittest discover
